model_path:
  small: "./models/Llama-SEA-LION-v2-8B-IT-Q3_K_M.gguf"
  large: "./models/Llama-SEA-LION-v2-8B-IT-Q5_K_M.gguf"

model_type: "llama"

embeddings_path: "BAAI/bge-large-en-v1.5"

model_config: 
  'max_new_tokens': 512
  'temperature' : 0
  'context_length': 8192
  'gpu_layers' : 0

chat_history_path: "./chat_sessions"